package kg.storekey.secure_key;

public enum AppKeyPairErrors {
    NOT_FOUND,
    CREATE_FAIL,
    CREATE_FAIL_NOT_FOUND,
    REMOVE_FAIL,
    PRIVATE_KEY_NOT_FOUND,
    DECODE_INPUT_NULL,
    PUBLIC_KEY_NOT_FOUND,
    SIGNATURE_FAIL,

    ENCRYPTION_FAIL,
    DECRYPTION_FAIL,
    BAD_ARGS,
    UNKNOWN,
    NOT_INIT,
    INIT
}
